//  Created by Kieran Halliday on 2018-06-05.
//  Copyright © 2018 Kieran Halliday. All rights reserved.
//
//Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
//
//22=4, 23=8, 24=16, 25=32
//32=9, 33=27, 34=81, 35=243
//42=16, 43=64, 44=256, 45=1024
//52=25, 53=125, 54=625, 55=3125
//
//If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
//
//4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
//
//How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?


#include <iostream>
#include <math.h>
#include <vector>
#include <set>

using namespace std;

const int LOWER_LIMIT = 2;
const int UPPER_LIMIT = 100;

set<double> terms;

int main(int argc, const char * argv[]) {
	for(int i=LOWER_LIMIT;i<=UPPER_LIMIT;i++){
		for(int j=LOWER_LIMIT;j<=UPPER_LIMIT;j++){
			terms.insert(pow((double) i, (double) j));
		}
	}

	cout << terms.size() << endl;
	return 0;
}
